const QUESTIONS = [
    {
      id: "q1",
      risk: "red",
      timeLimit: 20,
      prompt:
        "¿Cuál es la tolerancia de alcohol en sangre permitida para conducir un automóvil particular en la Provincia de Santa Fe?",
      options: [
        { id: "a", text: "0,0 g/l (tolerancia cero)", correct: false },
        { id: "b", text: "0,2 g/l", correct: false },
        { id: "c", text: "0,5 g/l", correct: true },
      ],
      explanation:
        "La normativa provincial establece tolerancia de hasta 0,5 g/l para conductores particulares. El alcohol afecta reflejos y aumenta exponencialmente el riesgo de siniestros.",
      resources: [
        { title: "Informe ANSV Siniestralidad (2021)", url: "https://www.argentina.gob.ar/sites/default/files/2018/12/ansv_informe_siniestralidad-vial_fatal_2021_datos_preliminares.pdf" },
      ],
    },
    {
      id: "q2",
      risk: "yellow",
      timeLimit: 25,
      prompt:
        "Te aproximás a una bocacalle sin semáforo ni señalización. ¿Quién tiene prioridad de paso?",
      options: [
        { id: "a", text: "El que llega primero, sin importar el lado", correct: false },
        { id: "b", text: "El vehículo que se aproxima por la derecha", correct: true },
        { id: "c", text: "El de mayor tamaño", correct: false },
      ],
      explanation: "Ante ausencia de señalización, rige la prioridad de paso para quien circula por la derecha.",
      resources: [
        { title: "Manual del conductor - Santa Fe", url: "https://www.santafe.gov.ar/index.php/educacion/content/download/234217/1232006/file/Manual%20Conductor.pdf" },
      ],
    },
    {
      id: "q3",
      risk: "green",
      timeLimit: 20,
      prompt: "¿Qué indica la señal de tránsito de fondo azul con una 'P' blanca?",
      options: [
        { id: "a", text: "Prohibido estacionar", correct: false },
        { id: "b", text: "Estacionamiento permitido", correct: true },
        { id: "c", text: "Zona de carga y descarga", correct: false },
      ],
      explanation: "La señal azul con 'P' indica zona habilitada para estacionar.",
      resources: [],
    },
  
    
        {
          id: "q4",
          risk: "yellow",
          prompt: "¿Qué significa esta señal?",
          image: "https://www.santafe.gob.ar/examenlicencia/examenETLC/images/preguntas/a95c2d71610bc718f59f87c0095a5789c704bc92.jpg",
          options: [
            { id: "a", text: "Detención Cruce de caminos.", correct: false },
            { id: "b", text: "Cruce de varias vías férreas. Paso a nivel peligroso.", correct: true },
            { id: "c", text: "Puente ferroviario.", correct: false },
          ],
          explanation: "La señal indica cruce de varias vías férreas, advirtiendo un alto riesgo en la zona.",
          impactImage: "/images/impact/train_accident.jpg",
          resources: [{ title: "Ley 24.449 - Señalización ferroviaria", url: "https://www.argentina.gob.ar/normativa/nacional/ley-24449-76338/texto" }],
        },
        {
          id: "q5",
          risk: "red",
          prompt: "¿En caso de que un inspector de tránsito indique circular traspasando el semáforo en rojo?",
          options: [
            { id: "a", text: "Debe respetar la indicación de la autoridad de comprobación.", correct: true },
            { id: "b", text: "Debe respetar la señal de tránsito como corresponde.", correct: false },
            { id: "c", text: "Rige la norma legal en el caso particular.", correct: false },
          ],
          explanation: "La autoridad presente prevalece sobre la señalización vial en casos específicos.",
          impactImage: "/images/impact/red_light_accident.jpg",
          resources: [{ title: "Ley 24.449 - Autoridad de tránsito", url: "https://www.argentina.gob.ar/normativa/nacional/ley-24449-76338/texto" }],
        },
        {
          id: "q6",
          risk: "yellow",
          prompt: "¿Qué significa esta señal?",
          image: "https://www.santafe.gob.ar/examenlicencia/examenETLC/images/preguntas/027b8890a45d74fa189dddace2be93bcdb608860.jpg",
          options: [
            { id: "a", text: "Prohibido circular autos.", correct: false },
            { id: "b", text: "Precaución vía de un sólo carril.", correct: false },
            { id: "c", text: "Prohibido adelantarse.", correct: true },
          ],
          explanation: "La señal prohíbe adelantar en ese tramo, por riesgo de colisión frontal.",
          impactImage: "/images/impact/headon_collision.jpg",
          resources: [{ title: "ANSV - Señales reglamentarias", url: "https://www.argentina.gob.ar/seguridadvial" }],
        },
        {
          id: "q7",
          risk: "green",
          prompt: "¿A qué se denomina vías multicarriles?",
          options: [
            { id: "a", text: "Son aquellas que disponen de tres o más carriles por manos.", correct: false },
            { id: "b", text: "Son aquellas que disponen de dos o más carriles por mano.", correct: true },
            { id: "c", text: "Son aquellas que disponen de más de 5 carriles.", correct: false },
          ],
          explanation: "Una vía multicarril es aquella con al menos dos carriles por mano.",
          impactImage: "/images/impact/traffic.jpg",
          resources: [],
        },
        {
          id: "q8",
          risk: "red",
          prompt: "¿Qué condiciones facilitan la fatiga en el conductor?",
          options: [
            { id: "a", text: "Conducir muy despacio", correct: false },
            { id: "b", text: "Viajar sin acompañantes o pasajeros.", correct: false },
            { id: "c", text: "Disminuir descansos, monotonía, incomodidad, estado psicofísico no óptimo.", correct: true },
          ],
          explanation: "La fatiga incrementa el riesgo de accidente por distracción o somnolencia.",
          impactImage: "/images/impact/fatigue.jpg",
          resources: [{ title: "OMS - Seguridad vial y fatiga", url: "https://www.who.int/es" }],
        },
        {
          id: "q9",
          risk: "red",
          prompt:
            "Según la Ley Provincial Nº 13.169, ¿la multa por alcoholemia positiva grave puede cancelarse completamente mediante pago voluntario con descuento?",
          options: [
            { id: "a", text: "Sí, ya que el pago voluntario implica el reconocimiento de la infracción.", correct: false },
            { id: "b", text: "No, el presunto infractor debe necesariamente comparecer ante el juez.", correct: true },
            { id: "c", text: "Sí, sólo si el pago voluntario se efectiviza dentro de los 30 días.", correct: false },
          ],
          explanation: "Para casos graves de alcoholemia no aplica pago voluntario con beneficio de descuento; corresponde comparecer ante la autoridad competente.",
          resources: [],
        },
        {
          id: "q10",
          risk: "green",
          prompt: "¿A qué se denomina Paso a Nivel?",
          options: [
            { id: "a", text: "El cruce de una vía de circulación con el ferrocarril.", correct: true },
            { id: "b", text: "El cruce de una vía de circulación.", correct: false },
            { id: "c", text: "El cruce de una vía de circulación con o sin el ferrocarril.", correct: false },
          ],
          explanation: "Un paso a nivel es el cruce al mismo nivel entre una vía de circulación y una vía férrea.",
          resources: [],
        },
        {
          id: "q11",
          risk: "green",
          prompt: "Las señales reglamentarias:",
          options: [
            { id: "a", text: "Advierten proximidad de peligros y requieren adecuar la conducción.", correct: false },
            { id: "b", text: "Transmiten órdenes de carácter obligatorio en el lugar destinado.", correct: true },
            { id: "c", text: "Brindan información de servicios y distancias.", correct: false },
          ],
          explanation: "Las señales reglamentarias son de cumplimiento obligatorio (prohibiciones, obligaciones, restricciones).",
          resources: [],
        },
        {
          id: "q12",
          risk: "yellow",
          prompt:
            "Una autoridad de tránsito intentó retener mi vehículo con alcoholemia de 0,10 g/l (auto particular, documentación y vehículo en condiciones). ¿Puede hacerlo?",
          options: [
            { id: "a", text: "No, estoy dentro de la tolerancia permitida para automóviles.", correct: true },
            { id: "b", text: "Sí, es una facultad de la autoridad de control.", correct: false },
            { id: "c", text: "Depende la bebida alcohólica consumida.", correct: false },
          ],
          explanation: "Para automóviles particulares rige tolerancia hasta 0,5 g/l; con 0,10 g/l no corresponde retención por alcoholemia.",
          resources: [],
        },
        {
          id: "q13",
          risk: "yellow",
          prompt: "¿Qué significa esta señal?",
          image: "https://www.santafe.gob.ar/examenlicencia/examenETLC/images/preguntas/05f9b91e44fd2401ed48711ad82e27ecfa132eab.jpg",
          options: [
            { id: "a", text: "Camino peligroso.", correct: false },
            { id: "b", text: "Pendiente peligrosa bajada.", correct: true },
            { id: "c", text: "Pendiente peligrosa subida.", correct: false },
          ],
          explanation: "La señal advierte una fuerte pendiente descendente que exige extremar precauciones.",
          resources: [],
        },
        {
          id: "q14",
          risk: "green",
          prompt: "¿Qué validez máxima tiene la licencia de conducir?",
          options: [
            { id: "a", text: "Hasta ocho (8) años.", correct: false },
            { id: "b", text: "Hasta cinco (5) años.", correct: true },
            { id: "c", text: "Hasta veinte (20) años.", correct: false },
          ],
          explanation: "La validez general máxima es de 5 años, sujeta a clase y franja etaria según normativa local.",
          resources: [],
        },
        {
          id: "q15",
          risk: "yellow",
          prompt:
            "Según la Ley Nacional Nº 24.449, ¿cuál es el límite mínimo de velocidad obligatorio para zona urbana y autopistas?",
          options: [
            { id: "a", text: "40 km/h, salvo vehículos con permisos y maquinarias especiales.", correct: false },
            { id: "b", text: "La mitad del máximo fijado para cada tipo de vía.", correct: true },
            { id: "c", text: "60 km/h.", correct: false },
          ],
          explanation: "El mínimo reglamentario suele establecerse como la mitad del máximo permitido en la vía.",
          resources: [],
        },
        {
          id: "q16",
          risk: "green",
          prompt: "La prioridad de paso a quien viene por la derecha es:",
          options: [
            { id: "a", text: "Una prioridad absoluta.", correct: false },
            { id: "b", text: "Absoluta que se pierde ante determinadas situaciones.", correct: true },
            { id: "c", text: "No es una prioridad.", correct: false },
          ],
          explanation: "La prioridad por la derecha rige con excepciones (rotondas, señalización, vehículos de emergencia, etc.).",
          resources: [],
        },
        {
          id: "q17",
          risk: "yellow",
          prompt: "¿Qué indican las líneas longitudinales continuas?",
          options: [
            { id: "a", text: "Sólo si son amarillas, no deben traspasarse.", correct: false },
            { id: "b", text: "Independientemente del color, no deben traspasarse ni circular sobre ellas.", correct: true },
            { id: "c", text: "Indican carriles o zonas de circulación.", correct: false },
          ],
          explanation: "Las líneas continuas prohíben cruzarlas y se respetan tanto en color blanco como amarillo.",
          resources: [],
        },
        {
          id: "q18",
          risk: "green",
          prompt: "Las señales transitorias:",
          options: [
            { id: "a", text: "Transmiten órdenes obligatorias.", correct: false },
            { id: "b", text: "Advierten peligros permanentes del camino.", correct: false },
            { id: "c", text: "Señalizan trabajos y ordenan la circulación en obras para evitar riesgos y demoras.", correct: true },
          ],
          explanation: "Las señales transitorias organizan la circulación en zonas de obras o mantenimiento.",
          resources: [],
        },
        {
          id: "q19",
          risk: "yellow",
          prompt:
            "En ruta detrás de un camión que hace señas manuales y/o luz de giro derecha para que lo pase, ¿qué se debe hacer?",
          options: [
            { id: "a", text: "Iniciar el adelantamiento con total seguridad.", correct: false },
            { id: "b", text: "Esperar hasta que encienda la luz de giro izquierda.", correct: false },
            { id: "c", text: "Permanecer en el carril hasta verificar personalmente que la vía está libre en distancia suficiente.", correct: true },
          ],
          explanation: "La decisión de adelantar depende de la propia verificación de condiciones seguras, no de señales de terceros.",
          resources: [],
        },
        {
          id: "q20",
          risk: "yellow",
          prompt: "¿Qué significa esta señal?",
          image: "https://www.santafe.gob.ar/examenlicencia/examenETLC/images/preguntas/50ddda20166f0636f63f80e1af68907c9e0102ff.jpg",
          options: [
            { id: "a", text: "Prohibido tracción a sangre.", correct: true },
            { id: "b", text: "Prohibido circulación de maquinaria agrícola.", correct: false },
            { id: "c", text: "Prohibido tránsito pesado.", correct: false },
          ],
          explanation: "La señal prohíbe la circulación de vehículos de tracción a sangre en el tramo indicado.",
          resources: [],
        },
        {
          id: "q21",
          risk: "yellow",
          prompt: "La señalización de líneas continuas y discontinuas paralelas indica:",
          options: [
            { id: "a", text: "Se puede traspasar desde el lado de discontinuas hacia el de continua, no en sentido inverso.", correct: true },
            { id: "b", text: "Se puede traspasar desde el lado de continua hacia el de discontinuas, no en sentido inverso.", correct: false },
            { id: "c", text: "Se puede traspasar en ambos sentidos sin inconvenientes.", correct: false },
          ],
          explanation: "Sólo está permitido cruzar la línea cuando del lado propio es discontinua; si es continua, está prohibido.",
          resources: [],
        },
        {
          id: "q22",
          risk: "green",
          prompt: "Las señales verticales de prevención transmiten:",
          options: [
            { id: "a", text: "Órdenes precisas.", correct: false },
            { id: "b", text: "Advertencias sobre características de la vía.", correct: true },
            { id: "c", text: "Prohibiciones.", correct: false },
          ],
          explanation: "Las de prevención alertan sobre riesgos o características particulares del camino.",
          resources: [],
        },
        {
          id: "q23",
          risk: "yellow",
          prompt: "¿Qué significa esta señal?",
          image: "https://www.santafe.gob.ar/examenlicencia/examenETLC/images/preguntas/c3574b12e349f4470919307f0600101b9a63f79b.jpg",
          options: [
            { id: "a", text: "Cruz de San Andrés (Cruce ferroviario)", correct: true },
            { id: "b", text: "Proximidad de cementerio.", correct: false },
            { id: "c", text: "Cruce de caminos.", correct: false },
          ],
          explanation: "La Cruz de San Andrés advierte cruce ferroviario a nivel.",
          resources: [],
        },
        {
          id: "q24",
          risk: "yellow",
          prompt:
            "¿Con qué licencia habilitante se permite arrastrar un remolque que no exceda los 750 kg?",
          options: [
            { id: "a", text: "Cualquier licencia excepto la clase A.", correct: false },
            { id: "b", text: "Licencia clase B1, únicamente.", correct: false },
            { id: "c", text: "Licencias clase B2, D2 y E1.", correct: true },
          ],
          explanation: "La clase B1 habilita a conducir automóviles y a remolcar hasta 750 kg de manera general.",
          resources: [],
        },
        {
          id: "q25",
          risk: "green",
          prompt: "Con licencia clase B1, ¿puedo conducir un furgón de 3.200 kg de peso?",
          options: [
            { id: "a", text: "No, sólo hasta 3000 kg.", correct: false },
            { id: "b", text: "Sólo si los 3200 kg son de tara.", correct: false },
            { id: "c", text: "Sí, siempre que no supere los 3500 kg de peso total.", correct: true },
          ],
          explanation: "La clase B1 habilita hasta 3500 kg de peso total (GVWR).",
          resources: [],
        },
        {
          id: "q26",
          risk: "red",
          prompt: "¿Puede un conductor llevar a menores de 10 años en los asientos delanteros?",
          options: [
            { id: "a", text: "Sí, usando un dispositivo homologado.", correct: false },
            { id: "b", text: "No.", correct: true },
            { id: "c", text: "En principio no, pero podría en una pick up.", correct: false },
          ],
          explanation: "Los menores deben viajar en asientos traseros con SRI acorde a su talla y peso.",
          resources: [],
        },
        {
          id: "q27",
          risk: "green",
          prompt: "¿En un automóvil, pueden viajar 9 personas mayores?",
          options: [
            { id: "a", text: "Sí.", correct: false },
            { id: "b", text: "No.", correct: true },
            { id: "c", text: "Sólo si cuatro fueran menores de 10 años.", correct: false },
          ],
          explanation: "La capacidad de ocupantes está limitada por la homologación del vehículo y cantidad de cinturones.",
          resources: [],
        },
        {
          id: "q28",
          risk: "yellow",
          prompt: "¿Qué defensas adicionales al paragolpes está permitido utilizar en una pick-up?",
          options: [
            { id: "a", text: "No está permitido utilizar defensas.", correct: true },
            { id: "b", text: "Las que vienen de fábrica.", correct: false },
            { id: "c", text: "Cualquier tipo de defensas.", correct: false },
          ],
          explanation: "Sólo son admisibles los elementos previstos por el fabricante y homologados para el modelo.",
          resources: [],
        },
        {
            id: "q29",
            risk: "yellow",
            prompt: "¿Qué significa esta señal?",
            image: "https://www.santafe.gob.ar/examenlicencia/examenETLC/images/preguntas/46aed63eb8c3892ee69d6b0a873689eddd355661.jpg",
            options: [
              { id: "a", text: "Prohibido girar a la izquierda.", correct: true },
              { id: "b", text: "Precaución curva.", correct: false },
              { id: "c", text: "Prohibido girar en U.", correct: false },
            ],
            explanation: "La señal indica prohibición de realizar giros hacia la izquierda.",
            resources: [],
          },
          {
            id: "q30",
            risk: "red",
            prompt: "En caso de niebla, se debe circular con:",
            options: [
              { id: "a", text: "Faros antinieblas y luces altas.", correct: false },
              { id: "b", text: "Luces altas o de largo alcance.", correct: false },
              { id: "c", text: "Luces bajas.", correct: true },
            ],
            explanation: "La luz baja evita el rebote lumínico en la niebla y mejora la visibilidad.",
            resources: [],
          },
          {
            id: "q31",
            risk: "yellow",
            prompt: "¿Qué medidas de precaución se deben tomar al conducir en caso de lluvia en ruta?",
            options: [
              { id: "a", text: "Colocar luces altas o de largo alcance para aumentar la visibilidad.", correct: false },
              { id: "b", text: "Disminuir la velocidad y aumentar la distancia entre vehículos.", correct: true },
              { id: "c", text: "Detener el vehículo sobre la banquina para resguardo.", correct: false },
            ],
            explanation: "En lluvia la distancia de frenado aumenta: se debe reducir la velocidad y aumentar la distancia de seguridad.",
            resources: [],
          },
          {
            id: "q32",
            risk: "red",
            prompt: "¿Qué indica la luz verde de un semáforo?",
            options: [
              { id: "a", text: "Indica que hay que avanzar, pero no se debe iniciar la marcha hasta tanto la encrucijada se encuentre despejada.", correct: true },
              { id: "b", text: "Indica que hay que detenerse si se estima que no se alcanzará a trasponer la encrucijada.", correct: false },
              { id: "c", text: "Indica que hay que avanzar aunque mi vehículo quede detenido en el medio obstruyendo la circulación de la calzada que cruza.", correct: false },
            ],
            explanation: "La luz verde habilita el paso siempre que la intersección esté despejada.",
            resources: [],
          },
          {
            id: "q33",
            risk: "red",
            prompt: "El conductor que se niegue a pruebas de alcoholemia debe ser sancionado por el juez:",
            options: [
              { id: "a", text: "Con pena de inhabilitación para conducir, sin multa.", correct: false },
              { id: "b", text: "Con pena de multa más inhabilitación para conducir.", correct: true },
              { id: "c", text: "Sólo con pena de multa.", correct: false },
            ],
            explanation: "Negarse a la prueba constituye una falta grave sancionada con multa e inhabilitación.",
            resources: [{ title: "Ley 24.449 - Art. 72", url: "https://www.argentina.gob.ar/normativa/nacional/ley-24449-76338/texto" }],
          },
          {
            id: "q34",
            risk: "yellow",
            prompt: "Las sendas para la circulación de ciclistas son:",
            options: [
              { id: "a", text: "De uso exclusivo de los ciclistas.", correct: true },
              { id: "b", text: "Para ser utilizadas por ciclistas y motociclistas.", correct: false },
              { id: "c", text: "Pueden ser invadidas por vehículos en casos excepcionales.", correct: false },
            ],
            explanation: "Las ciclovías son de uso exclusivo para bicicletas, reforzando la seguridad vial.",
            resources: [],
          },
          {
            id: "q35",
            risk: "yellow",
            prompt: "¿Qué significa esta señal?",
            image: "https://www.santafe.gob.ar/examenlicencia/examenETLC/images/preguntas/5e9424f134d12671ffc09ab8bc25089095398c05.jpg",
            options: [
              { id: "a", text: "Prohibido Estacionar.", correct: true },
              { id: "b", text: "Estacionamiento exclusivo de emergencias.", correct: false },
              { id: "c", text: "Prohibido Estacionar y Detenerse.", correct: false },
            ],
            explanation: "La señal prohíbe estacionar en la zona indicada, aunque sí se permite detenerse.",
            resources: [],
          },
          {
            id: "q36",
            risk: "green",
            prompt: "Las bolsas de aire o airbags:",
            options: [
              { id: "a", text: "Se activan en caso de incendio del vehículo.", correct: false },
              { id: "b", text: "Sirven para evitar que choquemos.", correct: false },
              { id: "c", text: "Absorben energía del impacto y protegen contra golpes con el interior del vehículo.", correct: true },
            ],
            explanation: "El airbag es un sistema de retención complementario que reduce lesiones en impactos frontales.",
            resources: [],
          },
          {
            id: "q37",
            risk: "green",
            prompt: "¿A qué se denomina vehículo automotor?",
            options: [
              { id: "a", text: "Todo vehículo de más de cuatro ruedas con motor y tracción propia.", correct: false },
              { id: "b", text: "Todo vehículo de más de dos ruedas con motor y tracción propia.", correct: true },
              { id: "c", text: "Todo vehículo de más de dos ruedas sin motor, sólo tracción sangre.", correct: false },
            ],
            explanation: "Vehículo automotor es todo aquel que se impulsa por un motor y no depende de tracción animal.",
            resources: [],
          },
          {
            id: "q38",
            risk: "yellow",
            prompt: "¿Qué significa esta señal?",
            image: "https://www.santafe.gob.ar/examenlicencia/examenETLC/images/preguntas/89c6d7d35ab20c44c46c0a4095d43c1b000a9223.jpg",
            options: [
              { id: "a", text: "Prohibido adelantarse.", correct: false },
              { id: "b", text: "Prohibido circular autos.", correct: false },
              { id: "c", text: "Conserve su derecha.", correct: true },
            ],
            explanation: "La señal indica la obligación de circular por la derecha, reforzando la seguridad en vías de doble sentido.",
            resources: [],
          }
      ];
      
  
  export default QUESTIONS;